# ruff: noqa
# Minimal Sphinx config for API markdown generation only.
# Reads the processed algopy stubs (generated by docs/api_build.py via scripts/generate_docs.py)
# and outputs markdown consumed by Starlight. Intentionally omits HTML themes and MyST.

from docutils import nodes

project = "Algorand Python"
copyright = "2024, Algorand Foundation"
author = "Algorand Foundation"

extensions = ["autodoc2"]

templates_path = []
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# autodoc2: points to stubs generated into docs/algopy-stubs/ by api_build.py
autodoc2_packages = [
    {
        "path": "../algopy-stubs",  # relative to docs/sphinx/; generated by api_build.py
        "module": "algopy",
        "auto_mode": True,
    },
]
autodoc2_docstring_parser_regexes = [(r".*", "myst")]
autodoc2_hidden_objects = ["undoc"]
autodoc2_hidden_regexes = [r".*\.__subclasshook__"]
autodoc2_module_all_regexes = [r"algopy.*"]
autodoc2_sort_names = True
autodoc2_class_inheritance = False


# -- pycon/doctest → python conversion hook ----------------------------------
# Starlight's Expressive Code doesn't support the "pycon" or "doctest" lexers.
# This hook converts those code blocks to plain Python and strips REPL prompts
# so syntax highlighting works correctly.


def _strip_pycon_prompts(text: str) -> str:
    cleaned: list[str] = []
    for line in text.splitlines():
        if line.startswith(">>> "):
            cleaned.append(line[4:])
        elif line.startswith(">>>"):
            cleaned.append(line[3:].lstrip())
        elif line.startswith("... "):
            cleaned.append(line[4:])
        elif line.startswith("..."):
            cleaned.append(line[3:].lstrip())
        else:
            cleaned.append(line)
    return "\n".join(cleaned)


def convert_pycon_blocks(app, doctree, docname):  # type: ignore[no-untyped-def]
    if app.builder.name != "markdown":
        return
    for node in list(doctree.traverse(nodes.literal_block)):
        if node.get("language") in {"pycon", "doctest"}:
            node["language"] = "python"
            node.children = [nodes.Text(_strip_pycon_prompts(node.astext()))]


def setup(app):  # type: ignore[no-untyped-def]
    app.connect("doctree-resolved", convert_pycon_blocks)
    return {"version": "1.0", "parallel_read_safe": True, "parallel_write_safe": True}