# AUTO GENERATED BY scripts/generate_stub_symtables.py, DO NOT EDIT
import typing
from collections.abc import Mapping, Sequence


class SymbolData(typing.NamedTuple):
    fullname: str
    module_public: bool


STUB_SYMTABLES: typing.Final[Mapping[str, Mapping[str, SymbolData]]] = {
    "algopy": {
        "UInt64": SymbolData(fullname="algopy._primitives.UInt64", module_public=True),
        "Bytes": SymbolData(fullname="algopy._primitives.Bytes", module_public=True),
        "BytesBacked": SymbolData(fullname="algopy._primitives.BytesBacked", module_public=True),
        "FixedBytes": SymbolData(fullname="algopy._primitives.FixedBytes", module_public=True),
        "String": SymbolData(fullname="algopy._primitives.String", module_public=True),
        "BigUInt": SymbolData(fullname="algopy._primitives.BigUInt", module_public=True),
        "OnCompleteAction": SymbolData(
            fullname="algopy._constants.OnCompleteAction", module_public=True
        ),
        "TransactionType": SymbolData(
            fullname="algopy._constants.TransactionType", module_public=True
        ),
        "Account": SymbolData(fullname="algopy._reference.Account", module_public=True),
        "Asset": SymbolData(fullname="algopy._reference.Asset", module_public=True),
        "Application": SymbolData(fullname="algopy._reference.Application", module_public=True),
        "Box": SymbolData(fullname="algopy._box.Box", module_public=True),
        "BoxRef": SymbolData(fullname="algopy._box.BoxRef", module_public=True),
        "BoxMap": SymbolData(fullname="algopy._box.BoxMap", module_public=True),
        "CompiledContract": SymbolData(
            fullname="algopy._compiled.CompiledContract", module_public=True
        ),
        "CompiledLogicSig": SymbolData(
            fullname="algopy._compiled.CompiledLogicSig", module_public=True
        ),
        "compile_contract": SymbolData(
            fullname="algopy._compiled.compile_contract", module_public=True
        ),
        "compile_logicsig": SymbolData(
            fullname="algopy._compiled.compile_logicsig", module_public=True
        ),
        "StateTotals": SymbolData(fullname="algopy._contract.StateTotals", module_public=True),
        "Contract": SymbolData(fullname="algopy._contract.Contract", module_public=True),
        "subroutine": SymbolData(fullname="algopy._hints.subroutine", module_public=True),
        "ImmutableFixedArray": SymbolData(
            fullname="algopy._native.ImmutableFixedArray", module_public=True
        ),
        "FixedArray": SymbolData(fullname="algopy._native.FixedArray", module_public=True),
        "ImmutableArray": SymbolData(fullname="algopy._native.ImmutableArray", module_public=True),
        "ReferenceArray": SymbolData(fullname="algopy._native.ReferenceArray", module_public=True),
        "Array": SymbolData(fullname="algopy._native.Array", module_public=True),
        "Struct": SymbolData(fullname="algopy._native.Struct", module_public=True),
        "zero_bytes": SymbolData(fullname="algopy._native.zero_bytes", module_public=True),
        "LocalState": SymbolData(fullname="algopy._state.LocalState", module_public=True),
        "GlobalState": SymbolData(fullname="algopy._state.GlobalState", module_public=True),
        "urange": SymbolData(fullname="algopy._unsigned_builtins.urange", module_public=True),
        "uenumerate": SymbolData(
            fullname="algopy._unsigned_builtins.uenumerate", module_public=True
        ),
        "OpUpFeeSource": SymbolData(fullname="algopy._util.OpUpFeeSource", module_public=True),
        "ensure_budget": SymbolData(fullname="algopy._util.ensure_budget", module_public=True),
        "log": SymbolData(fullname="algopy._util.log", module_public=True),
        "size_of": SymbolData(fullname="algopy._util.size_of", module_public=True),
        "TemplateVar": SymbolData(
            fullname="algopy._template_variables.TemplateVar", module_public=True
        ),
        "LogicSig": SymbolData(fullname="algopy._logic_sig.LogicSig", module_public=True),
        "logicsig": SymbolData(fullname="algopy._logic_sig.logicsig", module_public=True),
        "arc4": SymbolData(fullname="algopy.arc4", module_public=True),
        "gtxn": SymbolData(fullname="algopy.gtxn", module_public=True),
        "itxn": SymbolData(fullname="algopy.itxn", module_public=True),
        "op": SymbolData(fullname="algopy.op", module_public=True),
        "public": SymbolData(fullname="algopy.arc4.abimethod", module_public=True),
        "ARC4Contract": SymbolData(fullname="algopy.arc4.ARC4Contract", module_public=True),
        "Global": SymbolData(fullname="algopy.op.Global", module_public=True),
        "Txn": SymbolData(fullname="algopy.op.Txn", module_public=True),
    },
    "algopy._aliases": {
        "public": SymbolData(fullname="algopy.arc4.abimethod", module_public=True)
    },
    "algopy._box": {
        "_TKey": SymbolData(fullname="algopy._box._TKey", module_public=True),
        "_TValue": SymbolData(fullname="algopy._box._TValue", module_public=True),
        "Box": SymbolData(fullname="algopy._box.Box", module_public=True),
        "BoxRef": SymbolData(fullname="algopy._box.BoxRef", module_public=True),
        "BoxMap": SymbolData(fullname="algopy._box.BoxMap", module_public=True),
    },
    "algopy._compiled": {
        "CompiledContract": SymbolData(
            fullname="algopy._compiled.CompiledContract", module_public=True
        ),
        "CompiledLogicSig": SymbolData(
            fullname="algopy._compiled.CompiledLogicSig", module_public=True
        ),
        "compile_contract": SymbolData(
            fullname="algopy._compiled.compile_contract", module_public=True
        ),
        "compile_logicsig": SymbolData(
            fullname="algopy._compiled.compile_logicsig", module_public=True
        ),
    },
    "algopy._constants": {
        "OnCompleteAction": SymbolData(
            fullname="algopy._constants.OnCompleteAction", module_public=True
        ),
        "TransactionType": SymbolData(
            fullname="algopy._constants.TransactionType", module_public=True
        ),
    },
    "algopy._contract": {
        "StateTotals": SymbolData(fullname="algopy._contract.StateTotals", module_public=True),
        "Contract": SymbolData(fullname="algopy._contract.Contract", module_public=True),
    },
    "algopy._hints": {
        "_P": SymbolData(fullname="algopy._hints._P", module_public=True),
        "_R": SymbolData(fullname="algopy._hints._R", module_public=True),
        "subroutine": SymbolData(fullname="algopy._hints.subroutine", module_public=True),
        "__pure": SymbolData(fullname="algopy._hints.__pure", module_public=True),
    },
    "algopy._interfaces": {
        "_Validatable": SymbolData(fullname="algopy._interfaces._Validatable", module_public=True)
    },
    "algopy._logic_sig": {
        "LogicSig": SymbolData(fullname="algopy._logic_sig.LogicSig", module_public=True),
        "logicsig": SymbolData(fullname="algopy._logic_sig.logicsig", module_public=True),
    },
    "algopy._native": {
        "_TArrayItem": SymbolData(fullname="algopy._native._TArrayItem", module_public=True),
        "_TArrayLength": SymbolData(fullname="algopy._native._TArrayLength", module_public=True),
        "ImmutableFixedArray": SymbolData(
            fullname="algopy._native.ImmutableFixedArray", module_public=True
        ),
        "FixedArray": SymbolData(fullname="algopy._native.FixedArray", module_public=True),
        "ImmutableArray": SymbolData(fullname="algopy._native.ImmutableArray", module_public=True),
        "ReferenceArray": SymbolData(fullname="algopy._native.ReferenceArray", module_public=True),
        "Array": SymbolData(fullname="algopy._native.Array", module_public=True),
        "Struct": SymbolData(fullname="algopy._native.Struct", module_public=True),
        "zero_bytes": SymbolData(fullname="algopy._native.zero_bytes", module_public=True),
    },
    "algopy._primitives": {
        "UInt64": SymbolData(fullname="algopy._primitives.UInt64", module_public=True),
        "_BytesBase": SymbolData(fullname="algopy._primitives._BytesBase", module_public=True),
        "Bytes": SymbolData(fullname="algopy._primitives.Bytes", module_public=True),
        "BytesBacked": SymbolData(fullname="algopy._primitives.BytesBacked", module_public=True),
        "_TBytesLength": SymbolData(
            fullname="algopy._primitives._TBytesLength", module_public=True
        ),
        "FixedBytes": SymbolData(fullname="algopy._primitives.FixedBytes", module_public=True),
        "String": SymbolData(fullname="algopy._primitives.String", module_public=True),
        "BigUInt": SymbolData(fullname="algopy._primitives.BigUInt", module_public=True),
    },
    "algopy._reference": {
        "Account": SymbolData(fullname="algopy._reference.Account", module_public=True),
        "Asset": SymbolData(fullname="algopy._reference.Asset", module_public=True),
        "Application": SymbolData(fullname="algopy._reference.Application", module_public=True),
    },
    "algopy._state": {
        "_TState": SymbolData(fullname="algopy._state._TState", module_public=True),
        "LocalState": SymbolData(fullname="algopy._state.LocalState", module_public=True),
        "GlobalState": SymbolData(fullname="algopy._state.GlobalState", module_public=True),
    },
    "algopy._template_variables": {
        "_T_co": SymbolData(fullname="algopy._template_variables._T_co", module_public=True),
        "_TemplateVarMethod": SymbolData(
            fullname="algopy._template_variables._TemplateVarMethod", module_public=True
        ),
        "_TemplateVarGeneric": SymbolData(
            fullname="algopy._template_variables._TemplateVarGeneric", module_public=True
        ),
        "TemplateVar": SymbolData(
            fullname="algopy._template_variables.TemplateVar", module_public=True
        ),
    },
    "algopy._transaction": {
        "_TransactionBaseProtocol": SymbolData(
            fullname="algopy._transaction._TransactionBaseProtocol", module_public=True
        ),
        "_PaymentProtocol": SymbolData(
            fullname="algopy._transaction._PaymentProtocol", module_public=True
        ),
        "_KeyRegistrationProtocol": SymbolData(
            fullname="algopy._transaction._KeyRegistrationProtocol", module_public=True
        ),
        "_AssetConfigProtocol": SymbolData(
            fullname="algopy._transaction._AssetConfigProtocol", module_public=True
        ),
        "_AssetTransferProtocol": SymbolData(
            fullname="algopy._transaction._AssetTransferProtocol", module_public=True
        ),
        "_AssetFreezeProtocol": SymbolData(
            fullname="algopy._transaction._AssetFreezeProtocol", module_public=True
        ),
        "_ApplicationProtocol": SymbolData(
            fullname="algopy._transaction._ApplicationProtocol", module_public=True
        ),
    },
    "algopy._unsigned_builtins": {
        "urange": SymbolData(fullname="algopy._unsigned_builtins.urange", module_public=True),
        "_T": SymbolData(fullname="algopy._unsigned_builtins._T", module_public=True),
        "uenumerate": SymbolData(
            fullname="algopy._unsigned_builtins.uenumerate", module_public=True
        ),
    },
    "algopy._util": {
        "OpUpFeeSource": SymbolData(fullname="algopy._util.OpUpFeeSource", module_public=True),
        "ensure_budget": SymbolData(fullname="algopy._util.ensure_budget", module_public=True),
        "log": SymbolData(fullname="algopy._util.log", module_public=True),
        "size_of": SymbolData(fullname="algopy._util.size_of", module_public=True),
    },
    "algopy.arc4": {
        "_P": SymbolData(fullname="algopy.arc4._P", module_public=True),
        "_R": SymbolData(fullname="algopy.arc4._R", module_public=True),
        "_ReadOnlyNoArgsMethod": SymbolData(
            fullname="algopy.arc4._ReadOnlyNoArgsMethod", module_public=True
        ),
        "ARC4Contract": SymbolData(fullname="algopy.arc4.ARC4Contract", module_public=True),
        "abimethod": SymbolData(fullname="algopy.arc4.abimethod", module_public=True),
        "_TARC4Contract": SymbolData(fullname="algopy.arc4._TARC4Contract", module_public=True),
        "baremethod": SymbolData(fullname="algopy.arc4.baremethod", module_public=True),
        "arc4_signature": SymbolData(fullname="algopy.arc4.arc4_signature", module_public=True),
        "_ABIEncoded": SymbolData(fullname="algopy.arc4._ABIEncoded", module_public=True),
        "String": SymbolData(fullname="algopy.arc4.String", module_public=True),
        "_TBitSize": SymbolData(fullname="algopy.arc4._TBitSize", module_public=True),
        "_UIntN": SymbolData(fullname="algopy.arc4._UIntN", module_public=True),
        "UIntN": SymbolData(fullname="algopy.arc4.UIntN", module_public=True),
        "BigUIntN": SymbolData(fullname="algopy.arc4.BigUIntN", module_public=True),
        "_TDecimalPlaces": SymbolData(fullname="algopy.arc4._TDecimalPlaces", module_public=True),
        "UFixedNxM": SymbolData(fullname="algopy.arc4.UFixedNxM", module_public=True),
        "BigUFixedNxM": SymbolData(fullname="algopy.arc4.BigUFixedNxM", module_public=True),
        "Byte": SymbolData(fullname="algopy.arc4.Byte", module_public=True),
        "UInt8": SymbolData(fullname="algopy.arc4.UInt8", module_public=True),
        "UInt16": SymbolData(fullname="algopy.arc4.UInt16", module_public=True),
        "UInt32": SymbolData(fullname="algopy.arc4.UInt32", module_public=True),
        "UInt64": SymbolData(fullname="algopy.arc4.UInt64", module_public=True),
        "UInt128": SymbolData(fullname="algopy.arc4.UInt128", module_public=True),
        "UInt256": SymbolData(fullname="algopy.arc4.UInt256", module_public=True),
        "UInt512": SymbolData(fullname="algopy.arc4.UInt512", module_public=True),
        "Bool": SymbolData(fullname="algopy.arc4.Bool", module_public=True),
        "_TArrayItem": SymbolData(fullname="algopy.arc4._TArrayItem", module_public=True),
        "_TNativeArrayItem": SymbolData(
            fullname="algopy.arc4._TNativeArrayItem", module_public=True
        ),
        "_TArrayLength": SymbolData(fullname="algopy.arc4._TArrayLength", module_public=True),
        "StaticArray": SymbolData(fullname="algopy.arc4.StaticArray", module_public=True),
        "DynamicArray": SymbolData(fullname="algopy.arc4.DynamicArray", module_public=True),
        "Address": SymbolData(fullname="algopy.arc4.Address", module_public=True),
        "DynamicBytes": SymbolData(fullname="algopy.arc4.DynamicBytes", module_public=True),
        "_TTuple": SymbolData(fullname="algopy.arc4._TTuple", module_public=True),
        "Tuple": SymbolData(fullname="algopy.arc4.Tuple", module_public=True),
        "_StructMeta": SymbolData(fullname="algopy.arc4._StructMeta", module_public=True),
        "Struct": SymbolData(fullname="algopy.arc4.Struct", module_public=True),
        "ARC4Client": SymbolData(fullname="algopy.arc4.ARC4Client", module_public=True),
        "_TABIResult_co": SymbolData(fullname="algopy.arc4._TABIResult_co", module_public=True),
        "_ABICallWithReturnProtocol": SymbolData(
            fullname="algopy.arc4._ABICallWithReturnProtocol", module_public=True
        ),
        "_ABICallProtocolType": SymbolData(
            fullname="algopy.arc4._ABICallProtocolType", module_public=True
        ),
        "abi_call": SymbolData(fullname="algopy.arc4.abi_call", module_public=True),
        "arc4_create": SymbolData(fullname="algopy.arc4.arc4_create", module_public=True),
        "arc4_update": SymbolData(fullname="algopy.arc4.arc4_update", module_public=True),
        "emit": SymbolData(fullname="algopy.arc4.emit", module_public=True),
    },
    "algopy.gtxn": {
        "_GroupTransaction": SymbolData(
            fullname="algopy.gtxn._GroupTransaction", module_public=True
        ),
        "TransactionBase": SymbolData(fullname="algopy.gtxn.TransactionBase", module_public=True),
        "PaymentTransaction": SymbolData(
            fullname="algopy.gtxn.PaymentTransaction", module_public=True
        ),
        "KeyRegistrationTransaction": SymbolData(
            fullname="algopy.gtxn.KeyRegistrationTransaction", module_public=True
        ),
        "AssetConfigTransaction": SymbolData(
            fullname="algopy.gtxn.AssetConfigTransaction", module_public=True
        ),
        "AssetTransferTransaction": SymbolData(
            fullname="algopy.gtxn.AssetTransferTransaction", module_public=True
        ),
        "AssetFreezeTransaction": SymbolData(
            fullname="algopy.gtxn.AssetFreezeTransaction", module_public=True
        ),
        "ApplicationCallTransaction": SymbolData(
            fullname="algopy.gtxn.ApplicationCallTransaction", module_public=True
        ),
        "Transaction": SymbolData(fullname="algopy.gtxn.Transaction", module_public=True),
    },
    "algopy.itxn": {
        "PaymentInnerTransaction": SymbolData(
            fullname="algopy.itxn.PaymentInnerTransaction", module_public=True
        ),
        "KeyRegistrationInnerTransaction": SymbolData(
            fullname="algopy.itxn.KeyRegistrationInnerTransaction", module_public=True
        ),
        "AssetConfigInnerTransaction": SymbolData(
            fullname="algopy.itxn.AssetConfigInnerTransaction", module_public=True
        ),
        "AssetTransferInnerTransaction": SymbolData(
            fullname="algopy.itxn.AssetTransferInnerTransaction", module_public=True
        ),
        "AssetFreezeInnerTransaction": SymbolData(
            fullname="algopy.itxn.AssetFreezeInnerTransaction", module_public=True
        ),
        "ApplicationCallInnerTransaction": SymbolData(
            fullname="algopy.itxn.ApplicationCallInnerTransaction", module_public=True
        ),
        "InnerTransactionResult": SymbolData(
            fullname="algopy.itxn.InnerTransactionResult", module_public=True
        ),
        "_TResult_co": SymbolData(fullname="algopy.itxn._TResult_co", module_public=True),
        "_InnerTransaction": SymbolData(
            fullname="algopy.itxn._InnerTransaction", module_public=True
        ),
        "InnerTransaction": SymbolData(
            fullname="algopy.itxn.InnerTransaction", module_public=True
        ),
        "Payment": SymbolData(fullname="algopy.itxn.Payment", module_public=True),
        "KeyRegistration": SymbolData(fullname="algopy.itxn.KeyRegistration", module_public=True),
        "AssetConfig": SymbolData(fullname="algopy.itxn.AssetConfig", module_public=True),
        "AssetTransfer": SymbolData(fullname="algopy.itxn.AssetTransfer", module_public=True),
        "AssetFreeze": SymbolData(fullname="algopy.itxn.AssetFreeze", module_public=True),
        "ApplicationCall": SymbolData(fullname="algopy.itxn.ApplicationCall", module_public=True),
        "_T1": SymbolData(fullname="algopy.itxn._T1", module_public=True),
        "_T2": SymbolData(fullname="algopy.itxn._T2", module_public=True),
        "_T3": SymbolData(fullname="algopy.itxn._T3", module_public=True),
        "_T4": SymbolData(fullname="algopy.itxn._T4", module_public=True),
        "_T5": SymbolData(fullname="algopy.itxn._T5", module_public=True),
        "_T6": SymbolData(fullname="algopy.itxn._T6", module_public=True),
        "_T7": SymbolData(fullname="algopy.itxn._T7", module_public=True),
        "_T8": SymbolData(fullname="algopy.itxn._T8", module_public=True),
        "_T9": SymbolData(fullname="algopy.itxn._T9", module_public=True),
        "_T10": SymbolData(fullname="algopy.itxn._T10", module_public=True),
        "_T11": SymbolData(fullname="algopy.itxn._T11", module_public=True),
        "_T12": SymbolData(fullname="algopy.itxn._T12", module_public=True),
        "_T13": SymbolData(fullname="algopy.itxn._T13", module_public=True),
        "_T14": SymbolData(fullname="algopy.itxn._T14", module_public=True),
        "_T15": SymbolData(fullname="algopy.itxn._T15", module_public=True),
        "_T16": SymbolData(fullname="algopy.itxn._T16", module_public=True),
        "submit_txns": SymbolData(fullname="algopy.itxn.submit_txns", module_public=True),
        "submit_staged": SymbolData(fullname="algopy.itxn.submit_staged", module_public=True),
    },
    "algopy.op": {
        "EC": SymbolData(fullname="algopy.op.EC", module_public=True),
        "Base64": SymbolData(fullname="algopy.op.Base64", module_public=True),
        "ECDSA": SymbolData(fullname="algopy.op.ECDSA", module_public=True),
        "MiMCConfigurations": SymbolData(
            fullname="algopy.op.MiMCConfigurations", module_public=True
        ),
        "VrfVerify": SymbolData(fullname="algopy.op.VrfVerify", module_public=True),
        "addw": SymbolData(fullname="algopy.op.addw", module_public=True),
        "app_opted_in": SymbolData(fullname="algopy.op.app_opted_in", module_public=True),
        "arg": SymbolData(fullname="algopy.op.arg", module_public=True),
        "balance": SymbolData(fullname="algopy.op.balance", module_public=True),
        "base64_decode": SymbolData(fullname="algopy.op.base64_decode", module_public=True),
        "bitlen": SymbolData(fullname="algopy.op.bitlen", module_public=True),
        "bsqrt": SymbolData(fullname="algopy.op.bsqrt", module_public=True),
        "btoi": SymbolData(fullname="algopy.op.btoi", module_public=True),
        "bzero": SymbolData(fullname="algopy.op.bzero", module_public=True),
        "concat": SymbolData(fullname="algopy.op.concat", module_public=True),
        "divmodw": SymbolData(fullname="algopy.op.divmodw", module_public=True),
        "divw": SymbolData(fullname="algopy.op.divw", module_public=True),
        "ecdsa_pk_decompress": SymbolData(
            fullname="algopy.op.ecdsa_pk_decompress", module_public=True
        ),
        "ecdsa_pk_recover": SymbolData(fullname="algopy.op.ecdsa_pk_recover", module_public=True),
        "ecdsa_verify": SymbolData(fullname="algopy.op.ecdsa_verify", module_public=True),
        "ed25519verify": SymbolData(fullname="algopy.op.ed25519verify", module_public=True),
        "ed25519verify_bare": SymbolData(
            fullname="algopy.op.ed25519verify_bare", module_public=True
        ),
        "err": SymbolData(fullname="algopy.op.err", module_public=True),
        "exit": SymbolData(fullname="algopy.op.exit", module_public=True),
        "exp": SymbolData(fullname="algopy.op.exp", module_public=True),
        "expw": SymbolData(fullname="algopy.op.expw", module_public=True),
        "extract": SymbolData(fullname="algopy.op.extract", module_public=True),
        "extract_uint16": SymbolData(fullname="algopy.op.extract_uint16", module_public=True),
        "extract_uint32": SymbolData(fullname="algopy.op.extract_uint32", module_public=True),
        "extract_uint64": SymbolData(fullname="algopy.op.extract_uint64", module_public=True),
        "falcon_verify": SymbolData(fullname="algopy.op.falcon_verify", module_public=True),
        "gaid": SymbolData(fullname="algopy.op.gaid", module_public=True),
        "getbit": SymbolData(fullname="algopy.op.getbit", module_public=True),
        "getbyte": SymbolData(fullname="algopy.op.getbyte", module_public=True),
        "gload_bytes": SymbolData(fullname="algopy.op.gload_bytes", module_public=True),
        "gload_uint64": SymbolData(fullname="algopy.op.gload_uint64", module_public=True),
        "itob": SymbolData(fullname="algopy.op.itob", module_public=True),
        "keccak256": SymbolData(fullname="algopy.op.keccak256", module_public=True),
        "mimc": SymbolData(fullname="algopy.op.mimc", module_public=True),
        "min_balance": SymbolData(fullname="algopy.op.min_balance", module_public=True),
        "mulw": SymbolData(fullname="algopy.op.mulw", module_public=True),
        "online_stake": SymbolData(fullname="algopy.op.online_stake", module_public=True),
        "replace": SymbolData(fullname="algopy.op.replace", module_public=True),
        "select_bytes": SymbolData(fullname="algopy.op.select_bytes", module_public=True),
        "select_uint64": SymbolData(fullname="algopy.op.select_uint64", module_public=True),
        "setbit_bytes": SymbolData(fullname="algopy.op.setbit_bytes", module_public=True),
        "setbit_uint64": SymbolData(fullname="algopy.op.setbit_uint64", module_public=True),
        "setbyte": SymbolData(fullname="algopy.op.setbyte", module_public=True),
        "sha256": SymbolData(fullname="algopy.op.sha256", module_public=True),
        "sha3_256": SymbolData(fullname="algopy.op.sha3_256", module_public=True),
        "sha512_256": SymbolData(fullname="algopy.op.sha512_256", module_public=True),
        "shl": SymbolData(fullname="algopy.op.shl", module_public=True),
        "shr": SymbolData(fullname="algopy.op.shr", module_public=True),
        "sqrt": SymbolData(fullname="algopy.op.sqrt", module_public=True),
        "substring": SymbolData(fullname="algopy.op.substring", module_public=True),
        "sumhash512": SymbolData(fullname="algopy.op.sumhash512", module_public=True),
        "vrf_verify": SymbolData(fullname="algopy.op.vrf_verify", module_public=True),
        "AcctParamsGet": SymbolData(fullname="algopy.op.AcctParamsGet", module_public=True),
        "AppGlobal": SymbolData(fullname="algopy.op.AppGlobal", module_public=True),
        "AppLocal": SymbolData(fullname="algopy.op.AppLocal", module_public=True),
        "AppParamsGet": SymbolData(fullname="algopy.op.AppParamsGet", module_public=True),
        "AssetHoldingGet": SymbolData(fullname="algopy.op.AssetHoldingGet", module_public=True),
        "AssetParamsGet": SymbolData(fullname="algopy.op.AssetParamsGet", module_public=True),
        "Block": SymbolData(fullname="algopy.op.Block", module_public=True),
        "Box": SymbolData(fullname="algopy.op.Box", module_public=True),
        "EllipticCurve": SymbolData(fullname="algopy.op.EllipticCurve", module_public=True),
        "GITxn": SymbolData(fullname="algopy.op.GITxn", module_public=True),
        "GTxn": SymbolData(fullname="algopy.op.GTxn", module_public=True),
        "Global": SymbolData(fullname="algopy.op.Global", module_public=True),
        "ITxn": SymbolData(fullname="algopy.op.ITxn", module_public=True),
        "ITxnCreate": SymbolData(fullname="algopy.op.ITxnCreate", module_public=True),
        "JsonRef": SymbolData(fullname="algopy.op.JsonRef", module_public=True),
        "Scratch": SymbolData(fullname="algopy.op.Scratch", module_public=True),
        "Txn": SymbolData(fullname="algopy.op.Txn", module_public=True),
        "VoterParamsGet": SymbolData(fullname="algopy.op.VoterParamsGet", module_public=True),
    },
    "typing": {
        "Match": SymbolData(fullname="typing.Match", module_public=True),
        "Pattern": SymbolData(fullname="typing.Pattern", module_public=True),
        "Any": SymbolData(fullname="typing.Any", module_public=True),
        "_Final": SymbolData(fullname="typing._Final", module_public=False),
        "final": SymbolData(fullname="typing.final", module_public=True),
        "TypeVar": SymbolData(fullname="typing.TypeVar", module_public=True),
        "_promote": SymbolData(fullname="typing._promote", module_public=False),
        "_SpecialForm": SymbolData(fullname="typing._SpecialForm", module_public=False),
        "Union": SymbolData(fullname="typing.Union", module_public=True),
        "Generic": SymbolData(fullname="typing.Generic", module_public=True),
        "Protocol": SymbolData(fullname="typing.Protocol", module_public=True),
        "Callable": SymbolData(fullname="typing.Callable", module_public=True),
        "Type": SymbolData(fullname="typing.Type", module_public=True),
        "NoReturn": SymbolData(fullname="typing.NoReturn", module_public=True),
        "ClassVar": SymbolData(fullname="typing.ClassVar", module_public=True),
        "Optional": SymbolData(fullname="typing.Optional", module_public=True),
        "Tuple": SymbolData(fullname="typing.Tuple", module_public=True),
        "Final": SymbolData(fullname="typing.Final", module_public=True),
        "Literal": SymbolData(fullname="typing.Literal", module_public=True),
        "TypedDict": SymbolData(fullname="typing.TypedDict", module_public=True),
        "Self": SymbolData(fullname="typing.Self", module_public=True),
        "Never": SymbolData(fullname="typing.Never", module_public=True),
        "Unpack": SymbolData(fullname="typing.Unpack", module_public=True),
        "Required": SymbolData(fullname="typing.Required", module_public=True),
        "NotRequired": SymbolData(fullname="typing.NotRequired", module_public=True),
        "TypeVarTuple": SymbolData(fullname="typing.TypeVarTuple", module_public=True),
        "ParamSpecArgs": SymbolData(fullname="typing.ParamSpecArgs", module_public=True),
        "ParamSpecKwargs": SymbolData(fullname="typing.ParamSpecKwargs", module_public=True),
        "ParamSpec": SymbolData(fullname="typing.ParamSpec", module_public=True),
        "Concatenate": SymbolData(fullname="typing.Concatenate", module_public=True),
        "TypeAlias": SymbolData(fullname="typing.TypeAlias", module_public=True),
        "TypeGuard": SymbolData(fullname="typing.TypeGuard", module_public=True),
        "NewType": SymbolData(fullname="typing.NewType", module_public=True),
        "_F": SymbolData(fullname="typing._F", module_public=False),
        "_P": SymbolData(fullname="typing._P", module_public=False),
        "_T": SymbolData(fullname="typing._T", module_public=False),
        "_FT": SymbolData(fullname="typing._FT", module_public=False),
        "_S": SymbolData(fullname="typing._S", module_public=False),
        "_KT": SymbolData(fullname="typing._KT", module_public=False),
        "_VT": SymbolData(fullname="typing._VT", module_public=False),
        "_T_co": SymbolData(fullname="typing._T_co", module_public=False),
        "_KT_co": SymbolData(fullname="typing._KT_co", module_public=False),
        "_VT_co": SymbolData(fullname="typing._VT_co", module_public=False),
        "_TC": SymbolData(fullname="typing._TC", module_public=False),
        "overload": SymbolData(fullname="typing.overload", module_public=True),
        "no_type_check": SymbolData(fullname="typing.no_type_check", module_public=True),
        "no_type_check_decorator": SymbolData(
            fullname="typing.no_type_check_decorator", module_public=True
        ),
        "type_check_only": SymbolData(fullname="typing.type_check_only", module_public=False),
        "_Alias": SymbolData(fullname="typing._Alias", module_public=False),
        "Annotated": SymbolData(fullname="typing.Annotated", module_public=True),
        "AnyStr": SymbolData(fullname="typing.AnyStr", module_public=True),
        "_ProtocolMeta": SymbolData(fullname="typing._ProtocolMeta", module_public=False),
        "runtime_checkable": SymbolData(fullname="typing.runtime_checkable", module_public=True),
        "SupportsInt": SymbolData(fullname="typing.SupportsInt", module_public=True),
        "SupportsFloat": SymbolData(fullname="typing.SupportsFloat", module_public=True),
        "SupportsComplex": SymbolData(fullname="typing.SupportsComplex", module_public=True),
        "SupportsBytes": SymbolData(fullname="typing.SupportsBytes", module_public=True),
        "SupportsIndex": SymbolData(fullname="typing.SupportsIndex", module_public=True),
        "SupportsAbs": SymbolData(fullname="typing.SupportsAbs", module_public=True),
        "SupportsRound": SymbolData(fullname="typing.SupportsRound", module_public=True),
        "Sized": SymbolData(fullname="typing.Sized", module_public=True),
        "Hashable": SymbolData(fullname="typing.Hashable", module_public=True),
        "Iterable": SymbolData(fullname="typing.Iterable", module_public=True),
        "Iterator": SymbolData(fullname="typing.Iterator", module_public=True),
        "Reversible": SymbolData(fullname="typing.Reversible", module_public=True),
        "_YieldT_co": SymbolData(fullname="typing._YieldT_co", module_public=False),
        "_SendT_contra": SymbolData(fullname="typing._SendT_contra", module_public=False),
        "_ReturnT_co": SymbolData(fullname="typing._ReturnT_co", module_public=False),
        "Generator": SymbolData(fullname="typing.Generator", module_public=True),
        "ContextManager": SymbolData(fullname="typing.ContextManager", module_public=True),
        "AsyncContextManager": SymbolData(
            fullname="typing.AsyncContextManager", module_public=True
        ),
        "Awaitable": SymbolData(fullname="typing.Awaitable", module_public=True),
        "_SendT_nd_contra": SymbolData(fullname="typing._SendT_nd_contra", module_public=False),
        "_ReturnT_nd_co": SymbolData(fullname="typing._ReturnT_nd_co", module_public=False),
        "Coroutine": SymbolData(fullname="typing.Coroutine", module_public=True),
        "AwaitableGenerator": SymbolData(
            fullname="typing.AwaitableGenerator", module_public=False
        ),
        "AsyncIterable": SymbolData(fullname="typing.AsyncIterable", module_public=True),
        "AsyncIterator": SymbolData(fullname="typing.AsyncIterator", module_public=True),
        "AsyncGenerator": SymbolData(fullname="typing.AsyncGenerator", module_public=True),
        "Container": SymbolData(fullname="typing.Container", module_public=True),
        "Collection": SymbolData(fullname="typing.Collection", module_public=True),
        "Sequence": SymbolData(fullname="typing.Sequence", module_public=True),
        "MutableSequence": SymbolData(fullname="typing.MutableSequence", module_public=True),
        "AbstractSet": SymbolData(fullname="typing.AbstractSet", module_public=True),
        "MutableSet": SymbolData(fullname="typing.MutableSet", module_public=True),
        "MappingView": SymbolData(fullname="typing.MappingView", module_public=True),
        "ItemsView": SymbolData(fullname="typing.ItemsView", module_public=True),
        "KeysView": SymbolData(fullname="typing.KeysView", module_public=True),
        "ValuesView": SymbolData(fullname="typing.ValuesView", module_public=True),
        "Mapping": SymbolData(fullname="typing.Mapping", module_public=True),
        "MutableMapping": SymbolData(fullname="typing.MutableMapping", module_public=True),
        "Text": SymbolData(fullname="typing.Text", module_public=True),
        "TYPE_CHECKING": SymbolData(fullname="typing.TYPE_CHECKING", module_public=True),
        "IO": SymbolData(fullname="typing.IO", module_public=True),
        "BinaryIO": SymbolData(fullname="typing.BinaryIO", module_public=True),
        "TextIO": SymbolData(fullname="typing.TextIO", module_public=True),
        "ByteString": SymbolData(fullname="typing.ByteString", module_public=True),
        "_get_type_hints_obj_allowed_types": SymbolData(
            fullname="typing._get_type_hints_obj_allowed_types", module_public=False
        ),
        "get_type_hints": SymbolData(fullname="typing.get_type_hints", module_public=True),
        "get_args": SymbolData(fullname="typing.get_args", module_public=True),
        "get_origin": SymbolData(fullname="typing.get_origin", module_public=True),
        "cast": SymbolData(fullname="typing.cast", module_public=True),
        "reveal_type": SymbolData(fullname="typing.reveal_type", module_public=True),
        "assert_never": SymbolData(fullname="typing.assert_never", module_public=True),
        "assert_type": SymbolData(fullname="typing.assert_type", module_public=True),
        "clear_overloads": SymbolData(fullname="typing.clear_overloads", module_public=True),
        "get_overloads": SymbolData(fullname="typing.get_overloads", module_public=True),
        "dataclass_transform": SymbolData(
            fullname="typing.dataclass_transform", module_public=True
        ),
        "NamedTuple": SymbolData(fullname="typing.NamedTuple", module_public=True),
        "_TypedDict": SymbolData(fullname="typing._TypedDict", module_public=False),
        "ForwardRef": SymbolData(fullname="typing.ForwardRef", module_public=True),
        "is_typeddict": SymbolData(fullname="typing.is_typeddict", module_public=True),
        "_type_repr": SymbolData(fullname="typing._type_repr", module_public=False),
        "override": SymbolData(fullname="typing.override", module_public=True),
        "TypeAliasType": SymbolData(fullname="typing.TypeAliasType", module_public=True),
        "List": SymbolData(fullname="typing.List", module_public=True),
        "Dict": SymbolData(fullname="typing.Dict", module_public=True),
        "Set": SymbolData(fullname="typing.Set", module_public=True),
        "FrozenSet": SymbolData(fullname="typing.FrozenSet", module_public=True),
        "LiteralString": SymbolData(fullname="typing.LiteralString", module_public=True),
    },
    "typing_extensions": {
        "AsyncGenerator": SymbolData(fullname="typing.AsyncGenerator", module_public=True),
        "AsyncIterable": SymbolData(fullname="typing.AsyncIterable", module_public=True),
        "AsyncIterator": SymbolData(fullname="typing.AsyncIterator", module_public=True),
        "Awaitable": SymbolData(fullname="typing.Awaitable", module_public=True),
        "Collection": SymbolData(fullname="typing.Collection", module_public=True),
        "Container": SymbolData(fullname="typing.Container", module_public=True),
        "Coroutine": SymbolData(fullname="typing.Coroutine", module_public=True),
        "Generator": SymbolData(fullname="typing.Generator", module_public=True),
        "Hashable": SymbolData(fullname="typing.Hashable", module_public=True),
        "ItemsView": SymbolData(fullname="typing.ItemsView", module_public=True),
        "Iterable": SymbolData(fullname="typing.Iterable", module_public=True),
        "Iterator": SymbolData(fullname="typing.Iterator", module_public=True),
        "KeysView": SymbolData(fullname="typing.KeysView", module_public=True),
        "Mapping": SymbolData(fullname="typing.Mapping", module_public=True),
        "MappingView": SymbolData(fullname="typing.MappingView", module_public=True),
        "MutableMapping": SymbolData(fullname="typing.MutableMapping", module_public=True),
        "MutableSequence": SymbolData(fullname="typing.MutableSequence", module_public=True),
        "MutableSet": SymbolData(fullname="typing.MutableSet", module_public=True),
        "Reversible": SymbolData(fullname="typing.Reversible", module_public=True),
        "Sequence": SymbolData(fullname="typing.Sequence", module_public=True),
        "Sized": SymbolData(fullname="typing.Sized", module_public=True),
        "ValuesView": SymbolData(fullname="typing.ValuesView", module_public=True),
        "AsyncContextManager": SymbolData(
            fullname="typing_extensions.AsyncContextManager", module_public=True
        ),
        "ContextManager": SymbolData(
            fullname="typing_extensions.ContextManager", module_public=True
        ),
        "Match": SymbolData(fullname="typing_extensions.Match", module_public=True),
        "Pattern": SymbolData(fullname="typing_extensions.Pattern", module_public=True),
        "IO": SymbolData(fullname="typing.IO", module_public=True),
        "TYPE_CHECKING": SymbolData(fullname="typing.TYPE_CHECKING", module_public=True),
        "AbstractSet": SymbolData(fullname="typing.AbstractSet", module_public=True),
        "Any": SymbolData(fullname="typing.Any", module_public=True),
        "AnyStr": SymbolData(fullname="typing.AnyStr", module_public=True),
        "BinaryIO": SymbolData(fullname="typing.BinaryIO", module_public=True),
        "Callable": SymbolData(fullname="typing.Callable", module_public=True),
        "ChainMap": SymbolData(fullname="typing_extensions.ChainMap", module_public=True),
        "ClassVar": SymbolData(fullname="typing.ClassVar", module_public=True),
        "Counter": SymbolData(fullname="typing_extensions.Counter", module_public=True),
        "DefaultDict": SymbolData(fullname="typing_extensions.DefaultDict", module_public=True),
        "Deque": SymbolData(fullname="typing_extensions.Deque", module_public=True),
        "Dict": SymbolData(fullname="typing.Dict", module_public=True),
        "ForwardRef": SymbolData(fullname="typing.ForwardRef", module_public=True),
        "FrozenSet": SymbolData(fullname="typing.FrozenSet", module_public=True),
        "Generic": SymbolData(fullname="typing.Generic", module_public=True),
        "List": SymbolData(fullname="typing.List", module_public=True),
        "NoReturn": SymbolData(fullname="typing.NoReturn", module_public=True),
        "Optional": SymbolData(fullname="typing.Optional", module_public=True),
        "Set": SymbolData(fullname="typing.Set", module_public=True),
        "Text": SymbolData(fullname="typing.Text", module_public=True),
        "TextIO": SymbolData(fullname="typing.TextIO", module_public=True),
        "Tuple": SymbolData(fullname="typing.Tuple", module_public=True),
        "Type": SymbolData(fullname="typing.Type", module_public=True),
        "TypedDict": SymbolData(fullname="typing.TypedDict", module_public=True),
        "Union": SymbolData(fullname="typing.Union", module_public=True),
        "cast": SymbolData(fullname="typing.cast", module_public=True),
        "no_type_check": SymbolData(fullname="typing.no_type_check", module_public=True),
        "no_type_check_decorator": SymbolData(
            fullname="typing.no_type_check_decorator", module_public=True
        ),
        "overload": SymbolData(fullname="typing.overload", module_public=True),
        "_T": SymbolData(fullname="typing_extensions._T", module_public=False),
        "_F": SymbolData(fullname="typing_extensions._F", module_public=False),
        "_TC": SymbolData(fullname="typing_extensions._TC", module_public=False),
        "_T_co": SymbolData(fullname="typing_extensions._T_co", module_public=False),
        "_T_contra": SymbolData(fullname="typing_extensions._T_contra", module_public=False),
        "_Final": SymbolData(fullname="typing_extensions._Final", module_public=False),
        "_SpecialForm": SymbolData(fullname="typing_extensions._SpecialForm", module_public=False),
        "Protocol": SymbolData(fullname="typing_extensions.Protocol", module_public=True),
        "runtime_checkable": SymbolData(
            fullname="typing_extensions.runtime_checkable", module_public=True
        ),
        "runtime": SymbolData(fullname="typing_extensions.runtime", module_public=True),
        "Final": SymbolData(fullname="typing_extensions.Final", module_public=True),
        "final": SymbolData(fullname="typing_extensions.final", module_public=True),
        "Literal": SymbolData(fullname="typing_extensions.Literal", module_public=True),
        "IntVar": SymbolData(fullname="typing_extensions.IntVar", module_public=True),
        "_TypedDict": SymbolData(fullname="typing_extensions._TypedDict", module_public=False),
        "get_type_hints": SymbolData(
            fullname="typing_extensions.get_type_hints", module_public=True
        ),
        "get_args": SymbolData(fullname="typing_extensions.get_args", module_public=True),
        "get_origin": SymbolData(fullname="typing_extensions.get_origin", module_public=True),
        "Annotated": SymbolData(fullname="typing_extensions.Annotated", module_public=True),
        "_AnnotatedAlias": SymbolData(
            fullname="typing_extensions._AnnotatedAlias", module_public=False
        ),
        "Concatenate": SymbolData(fullname="typing.Concatenate", module_public=True),
        "ParamSpecArgs": SymbolData(fullname="typing.ParamSpecArgs", module_public=True),
        "ParamSpecKwargs": SymbolData(fullname="typing.ParamSpecKwargs", module_public=True),
        "TypeAlias": SymbolData(fullname="typing.TypeAlias", module_public=True),
        "TypeGuard": SymbolData(fullname="typing.TypeGuard", module_public=True),
        "is_typeddict": SymbolData(fullname="typing.is_typeddict", module_public=True),
        "LiteralString": SymbolData(fullname="typing.LiteralString", module_public=True),
        "NamedTuple": SymbolData(fullname="typing.NamedTuple", module_public=True),
        "Never": SymbolData(fullname="typing.Never", module_public=True),
        "NewType": SymbolData(fullname="typing.NewType", module_public=True),
        "NotRequired": SymbolData(fullname="typing.NotRequired", module_public=True),
        "Required": SymbolData(fullname="typing.Required", module_public=True),
        "Self": SymbolData(fullname="typing.Self", module_public=True),
        "Unpack": SymbolData(fullname="typing.Unpack", module_public=True),
        "assert_never": SymbolData(fullname="typing.assert_never", module_public=True),
        "assert_type": SymbolData(fullname="typing.assert_type", module_public=True),
        "clear_overloads": SymbolData(fullname="typing.clear_overloads", module_public=True),
        "dataclass_transform": SymbolData(
            fullname="typing.dataclass_transform", module_public=True
        ),
        "get_overloads": SymbolData(fullname="typing.get_overloads", module_public=True),
        "reveal_type": SymbolData(fullname="typing.reveal_type", module_public=True),
        "Buffer": SymbolData(fullname="_collections_abc.Buffer", module_public=True),
        "get_original_bases": SymbolData(fullname="types.get_original_bases", module_public=True),
        "SupportsAbs": SymbolData(fullname="typing.SupportsAbs", module_public=True),
        "SupportsBytes": SymbolData(fullname="typing.SupportsBytes", module_public=True),
        "SupportsComplex": SymbolData(fullname="typing.SupportsComplex", module_public=True),
        "SupportsFloat": SymbolData(fullname="typing.SupportsFloat", module_public=True),
        "SupportsIndex": SymbolData(fullname="typing.SupportsIndex", module_public=True),
        "SupportsInt": SymbolData(fullname="typing.SupportsInt", module_public=True),
        "SupportsRound": SymbolData(fullname="typing.SupportsRound", module_public=True),
        "override": SymbolData(fullname="typing.override", module_public=True),
        "Reader": SymbolData(fullname="typing_extensions.Reader", module_public=True),
        "Writer": SymbolData(fullname="typing_extensions.Writer", module_public=True),
        "is_protocol": SymbolData(fullname="typing_extensions.is_protocol", module_public=True),
        "get_protocol_members": SymbolData(
            fullname="typing_extensions.get_protocol_members", module_public=True
        ),
        "_NoDefaultType": SymbolData(
            fullname="typing_extensions._NoDefaultType", module_public=False
        ),
        "NoDefault": SymbolData(fullname="typing_extensions.NoDefault", module_public=True),
        "CapsuleType": SymbolData(fullname="typing_extensions.CapsuleType", module_public=True),
        "deprecated": SymbolData(fullname="typing_extensions.deprecated", module_public=True),
        "TypeVar": SymbolData(fullname="typing_extensions.TypeVar", module_public=True),
        "ParamSpec": SymbolData(fullname="typing_extensions.ParamSpec", module_public=True),
        "TypeVarTuple": SymbolData(fullname="typing_extensions.TypeVarTuple", module_public=True),
        "ReadOnly": SymbolData(fullname="typing_extensions.ReadOnly", module_public=True),
        "TypeIs": SymbolData(fullname="typing_extensions.TypeIs", module_public=True),
        "TypeAliasType": SymbolData(
            fullname="typing_extensions.TypeAliasType", module_public=True
        ),
        "Doc": SymbolData(fullname="typing_extensions.Doc", module_public=True),
        "_NoExtraItemsType": SymbolData(
            fullname="typing_extensions._NoExtraItemsType", module_public=False
        ),
        "NoExtraItems": SymbolData(fullname="typing_extensions.NoExtraItems", module_public=True),
        "TypeForm": SymbolData(fullname="typing_extensions.TypeForm", module_public=True),
        "Format": SymbolData(fullname="typing_extensions.Format", module_public=True),
        "get_annotations": SymbolData(
            fullname="typing_extensions.get_annotations", module_public=True
        ),
        "evaluate_forward_ref": SymbolData(
            fullname="typing_extensions.evaluate_forward_ref", module_public=True
        ),
        "Sentinel": SymbolData(fullname="typing_extensions.Sentinel", module_public=True),
    },
    "abc": {
        "_T": SymbolData(fullname="abc._T", module_public=True),
        "_R_co": SymbolData(fullname="abc._R_co", module_public=True),
        "_FuncT": SymbolData(fullname="abc._FuncT", module_public=True),
        "_P": SymbolData(fullname="abc._P", module_public=True),
        "ABCMeta": SymbolData(fullname="abc.ABCMeta", module_public=True),
        "abstractmethod": SymbolData(fullname="abc.abstractmethod", module_public=True),
        "abstractclassmethod": SymbolData(fullname="abc.abstractclassmethod", module_public=True),
        "abstractstaticmethod": SymbolData(
            fullname="abc.abstractstaticmethod", module_public=True
        ),
        "abstractproperty": SymbolData(fullname="abc.abstractproperty", module_public=True),
        "ABC": SymbolData(fullname="abc.ABC", module_public=True),
        "get_cache_token": SymbolData(fullname="abc.get_cache_token", module_public=True),
        "update_abstractmethods": SymbolData(
            fullname="abc.update_abstractmethods", module_public=True
        ),
    },
}

STUB_DEPENDENCIES: typing.Final[Mapping[str, Sequence[str]]] = {
    "algopy": [
        "abc",
        "algopy._aliases",
        "algopy._box",
        "algopy._compiled",
        "algopy._constants",
        "algopy._contract",
        "algopy._hints",
        "algopy._interfaces",
        "algopy._logic_sig",
        "algopy._native",
        "algopy._primitives",
        "algopy._reference",
        "algopy._state",
        "algopy._template_variables",
        "algopy._unsigned_builtins",
        "algopy._util",
        "algopy.arc4",
        "algopy.gtxn",
        "algopy.itxn",
        "algopy.op",
        "typing",
    ],
    "algopy._aliases": ["abc", "algopy.arc4", "typing"],
    "algopy._box": ["abc", "algopy", "algopy._primitives", "typing", "typing_extensions"],
    "algopy._compiled": [
        "abc",
        "algopy",
        "algopy._contract",
        "algopy._interfaces",
        "algopy._logic_sig",
        "algopy._primitives",
        "algopy._reference",
        "typing",
    ],
    "algopy._constants": ["abc", "algopy", "algopy._primitives", "typing"],
    "algopy._contract": [
        "abc",
        "algopy",
        "algopy._primitives",
        "algopy._unsigned_builtins",
        "typing",
    ],
    "algopy._hints": ["abc", "typing"],
    "algopy._interfaces": ["abc", "typing"],
    "algopy._logic_sig": [
        "abc",
        "algopy",
        "algopy._primitives",
        "algopy._unsigned_builtins",
        "typing",
    ],
    "algopy._native": ["abc", "algopy", "algopy._interfaces", "algopy._primitives", "typing"],
    "algopy._primitives": ["abc", "algopy._interfaces", "typing"],
    "algopy._reference": ["abc", "algopy", "algopy._interfaces", "algopy._primitives", "typing"],
    "algopy._state": [
        "abc",
        "algopy",
        "algopy._interfaces",
        "algopy._primitives",
        "algopy._reference",
        "typing",
    ],
    "algopy._template_variables": ["abc", "typing"],
    "algopy._transaction": [
        "abc",
        "algopy",
        "algopy._constants",
        "algopy._interfaces",
        "algopy._primitives",
        "algopy._reference",
        "typing",
    ],
    "algopy._unsigned_builtins": ["abc", "algopy", "algopy._primitives", "typing"],
    "algopy._util": ["abc", "algopy", "algopy._primitives", "typing"],
    "algopy.arc4": [
        "abc",
        "algopy",
        "algopy._compiled",
        "algopy._constants",
        "algopy._contract",
        "algopy._interfaces",
        "algopy._native",
        "algopy._primitives",
        "algopy._reference",
        "algopy._transaction",
        "algopy._unsigned_builtins",
        "algopy.itxn",
        "typing",
        "typing_extensions",
    ],
    "algopy.gtxn": ["abc", "algopy", "algopy._primitives", "algopy._transaction", "typing"],
    "algopy.itxn": [
        "abc",
        "algopy",
        "algopy._constants",
        "algopy._interfaces",
        "algopy._primitives",
        "algopy._reference",
        "algopy._transaction",
        "typing",
    ],
    "algopy.op": [
        "abc",
        "algopy",
        "algopy._constants",
        "algopy._interfaces",
        "algopy._primitives",
        "algopy._reference",
        "typing",
    ],
    "typing": ["abc", "typing_extensions"],
    "typing_extensions": ["abc", "typing"],
    "abc": ["typing", "typing_extensions"],
}
