repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        description: "code formatting"
        entry: poetry run ruff format
        require_serial: true
        language: system
        minimum_pre_commit_version: 2.9.2
        types_or: [ python, pyi ]
      - id: ruff
        name: ruff
        description: "code linting"
        entry: poetry run ruff check
        language: system
        "types": [python]
        args: [--fix, --no-cache]
        additional_dependencies: []
        minimum_pre_commit_version: "0"
      - id: mypy
        name: mypy
        description: "static type analysis"
        entry: poetry run mypy
        language: system
        types_or: [python, pyi]
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"
        exclude: '^(src/puyapy/(_vendor|_typeshed)/|stubs/algopy\.py|docs/algopy-stubs/)'
