import typing

from algopy import Bytes, String, UInt64

@typing.final
class OpUpFeeSource(UInt64):
    """Defines the source of fees for the OpUp utility."""

    GroupCredit: OpUpFeeSource = ...
    """Only the excess fee (credit) on the outer group should be used (set inner_tx.fee=0)"""
    AppAccount: OpUpFeeSource = ...
    """The app's account will cover all fees (set inner_tx.fee=Global.min_tx_fee())"""
    Any: OpUpFeeSource = ...
    """First the excess will be used, remaining fees will be taken from the app account"""

def ensure_budget(required_budget: UInt64 | int, fee_source: OpUpFeeSource = ...) -> None:
    """Ensure the available op code budget is greater than or equal to required_budget"""

def log(*args: object, sep: String | str | Bytes | bytes = "") -> None:
    """Concatenates and logs supplied args as a single bytes value.

    UInt64 args are converted to bytes and each argument is separated by `sep`.
    Literal `str` values will be encoded as UTF8.
    """

def size_of(type_or_expression: type | object, /) -> UInt64:
    """
    Returns the number of bytes required to store a statically sized type,
    given as a type object or an expression of that type.
    """

def logged_assert(
    condition: bool,
    /,
    error_code: typing.LiteralString,
    error_message: typing.LiteralString | None = None,
    prefix: typing.Literal["AER", "ERR"] = "ERR",
) -> None:
    """
    Asserts that a condition is true, logging a formatted error message before failing
    if the condition is false.

    The logged output follows the format ``{prefix}:{error_code}`` or
    ``{prefix}:{error_code}:{error_message}`` and is compatible with ARC-56 and ARC-32 clients.

    Note this increases the generated bytecode, so keeping ``error_code`` and ``error_message``
    short is recommended.

    :arg condition: The condition to assert; if false, logs an error and fails.
    :arg error_code: An alphanumeric error code. Must not contain ``:``.
    :arg error_message: Optional message appended after the code. Must not contain ``:``.
    :arg prefix: Error prefix, either ``"AER"`` or ``"ERR"``.
    """

def logged_err(
    error_code: typing.LiteralString,
    error_message: typing.LiteralString | None = None,
    prefix: typing.Literal["AER", "ERR"] = "ERR",
) -> None:
    """
    Logs a formatted error message and immediately fails the transaction.

    Note this is equivalent to ``logged_assert(False, error_code, error_message, prefix)``.
    This function increases the generated bytecode, so keeping ``error_code`` and ``error_message``
    short is recommended.

    The logged output follows the ARC-65 format ``{prefix}:{error_code}`` or
    ``{prefix}:{error_code}:{error_message}`` and is compatible with ARC-56 and ARC-32 clients.

    :arg error_code: An alphanumeric error code. Must not contain ``:``.
    :arg error_message: Optional message appended after the code. Must not contain ``:``.
    :arg prefix: Error prefix, either ``"AER"`` or ``"ERR"``.
    """
