# AUTO GENERATED BY scripts/generate_puya_lib.py, DO NOT EDIT
# ruff: noqa: E501
# fmt: off

import enum


@enum.unique
class PuyaLibIR(enum.StrEnum):
    ensure_budget = "_puya_lib.util.ensure_budget"
    is_substring = "_puya_lib.bytes_.is_substring"
    box_dynamic_array_pop_fixed_size = "_puya_lib.box_arc4.box_dynamic_array_pop_fixed_size"
    box_dynamic_array_concat_fixed = "_puya_lib.box_arc4.box_dynamic_array_concat_fixed"
    box_update_offset_dec = "_puya_lib.box_arc4.box_update_offset_dec"
    box_update_offset_inc = "_puya_lib.box_arc4.box_update_offset_inc"
    dynamic_array_pop_bit = "_puya_lib.arc4.dynamic_array_pop_bit"
    r_trim = "_puya_lib.arc4.r_trim"
    dynamic_array_pop_fixed_size = "_puya_lib.arc4.dynamic_array_pop_fixed_size"
    dynamic_array_pop_byte_length_head = "_puya_lib.arc4.dynamic_array_pop_byte_length_head"
    dynamic_array_pop_dynamic_element = "_puya_lib.arc4.dynamic_array_pop_dynamic_element"
    dynamic_array_read_dynamic_element = "_puya_lib.arc4.dynamic_array_read_dynamic_element"
    static_array_read_dynamic_element = "_puya_lib.arc4.static_array_read_dynamic_element"
    dynamic_array_read_byte_length_element = "_puya_lib.arc4.dynamic_array_read_byte_length_element"
    static_array_read_byte_length_element = "_puya_lib.arc4.static_array_read_byte_length_element"
    dynamic_array_concat_fixed = "_puya_lib.arc4.dynamic_array_concat_fixed"
    dynamic_array_concat_bits = "_puya_lib.arc4.dynamic_array_concat_bits"
    dynamic_array_concat_byte_length_head = "_puya_lib.arc4.dynamic_array_concat_byte_length_head"
    dynamic_array_concat_dynamic_element = "_puya_lib.arc4.dynamic_array_concat_dynamic_element"
    dynamic_array_replace_byte_length_head = "_puya_lib.arc4.dynamic_array_replace_byte_length_head"
    dynamic_array_replace_dynamic_element = "_puya_lib.arc4.dynamic_array_replace_dynamic_element"
    static_array_replace_dynamic_element = "_puya_lib.arc4.static_array_replace_dynamic_element"
    static_array_replace_byte_length_head = "_puya_lib.arc4.static_array_replace_byte_length_head"
    dynamic_assert_index = "_puya_lib.arc4.dynamic_assert_index"
