from typing import Generic, TypeVar, TypeAlias

from algopy._primitives import Address, UInt64

_T = TypeVar("_T")

AccountIndex: TypeAlias = UInt64 | int

class Local(Generic[_T]):
    def __init__(self, type_: type[_T], /) -> None: ...
    def __getitem__(self, account: Address | AccountIndex) -> _T: ...
    def __setitem__(self, account: Address | AccountIndex, value: _T) -> None: ...
    def __delitem__(self, account: Address | AccountIndex) -> None: ...
    def __contains__(self, account: Address | AccountIndex) -> bool: ...
    def get(self, account: Address | AccountIndex, default: _T) -> _T: ...
    def maybe(self, account: Address | AccountIndex) -> tuple[_T, bool]: ...
