import algosdk.constants

ZERO_ADDRESS = algosdk.constants.ZERO_ADDRESS
ENCODED_ADDRESS_LENGTH = algosdk.constants.ADDRESS_LEN
MAX_BIGUINT_BITS = 512
MAX_BIGUINT_BYTES = MAX_BIGUINT_BITS // 8
MAX_BYTES_LENGTH = 4096
