name: "Build Linux Binary Artifacts"
description: "Build Linux specific pyinstaller binary artifacts using Docker container"
inputs:
  package_name:
    description: "The name of the package"
    required: true
  artifacts_dir:
    description: "The directory to write artifacts you want to publish"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set base image according to architecture
      id: set-base-image
      shell: bash
      run: |
        if [ "${{ runner.arch }}" == "ARM64" ]; then
          echo "BASE_IMAGE=quay.io/pypa/manylinux_2_28_aarch64" >> $GITHUB_OUTPUT
        else
          echo "BASE_IMAGE=quay.io/pypa/manylinux_2_28_x86_64" >> $GITHUB_OUTPUT
        fi

        # Set the cache tag based on architecture
        ARCH=$(echo "${{ runner.arch }}" | tr '[:upper:]' '[:lower:]')
        echo "CACHE_TAG=ghcr.io/${{ github.repository }}/puya-manylinux:${ARCH}" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_SUMMARY: false
      with:
        context: ${{ github.action_path }}
        file: ${{ github.action_path }}/Dockerfile
        build-args: |
          BASE_IMAGE=${{ steps.set-base-image.outputs.BASE_IMAGE }}
        push: true
        load: true
        tags: ${{ steps.set-base-image.outputs.CACHE_TAG }}
        cache-from: type=registry,ref=${{ steps.set-base-image.outputs.CACHE_TAG }}
        cache-to: type=registry,ref=${{ steps.set-base-image.outputs.CACHE_TAG }},mode=max

    - name: Run the container with the built image
      shell: bash
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/src \
          -v ${{ inputs.artifacts_dir }}:${{ inputs.artifacts_dir }} \
          -e GITHUB_WORKSPACE=/src \
          ${{ steps.set-base-image.outputs.CACHE_TAG }} \
          ${{ inputs.package_name }} \
          ${{ inputs.artifacts_dir }}

    - name: Package binary artifact
      shell: bash
      run: |
        cd dist/puya/
        tar -zcf ${{ inputs.artifacts_dir }}/${{ inputs.package_name }}.tar.gz *
        cd ../..

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.package_name }}
        path: ${{ inputs.artifacts_dir }}/${{ inputs.package_name }}.tar.gz
