#!/usr/bin/env python3
import json
import re
import subprocess
from collections.abc import Iterator, Sequence

import attrs

from puya import log
from puya.algo_constants import SUPPORTED_AVM_VERSIONS
from puyapy.awst_build import pytypes
from puyapy.awst_build.intrinsic_models import result_types_to_pytype
from scripts.script_utils import VCS_ROOT, autogenerated_header_for
from scripts.transform_lang_spec import (
    ArgEnum,
    Immediate,
    ImmediateKind,
    LanguageSpec,
    Op,
    StackType,
)

logger = log.get_logger(__name__)
INDENT = " " * 4
MIN_SUPPORTED_VERSION = min(SUPPORTED_AVM_VERSIONS)
ALGORAND_OP_URL = "https://dev.algorand.co/reference/algorand-teal/opcodes/"

PYTHON_ENUM_CLASS = {
    "Mimc Configurations": "MiMCConfigurations",
}

PYTYPE_TO_LITERAL: dict[pytypes.PyType, pytypes.LiteralOnlyType | None] = {
    pytypes.BytesType: pytypes.BytesLiteralType,
    pytypes.UInt64Type: pytypes.IntLiteralType,
    pytypes.AccountType: None,  # pytypes.StrLiteralType, # TODO: should we enable this?
    pytypes.BigUIntType: pytypes.IntLiteralType,
    pytypes.BoolType: None,  # already a Python type
    pytypes.ApplicationType: pytypes.IntLiteralType,
    pytypes.AssetType: pytypes.IntLiteralType,
    pytypes.TransactionTypeType: None,
    pytypes.OnCompleteActionType: None,
    pytypes.BytesBackedType: pytypes.BytesLiteralType,
}
PYTYPE_REPR = {
    value: f"pytypes.{key}"
    for key, value in pytypes.__dict__.items()
    if isinstance(value, pytypes.PyType)
}
STACK_TYPE_MAPPING: dict[StackType, Sequence[pytypes.PyType]] = {
    StackType.address_or_index: [pytypes.AccountType, pytypes.UInt64Type],
    StackType.application: [pytypes.ApplicationType, pytypes.UInt64Type],
    StackType.asset: [pytypes.AssetType, pytypes.UInt64Type],
    StackType.bytes: [pytypes.BytesType, pytypes.BytesBackedType],
    StackType.bytes_8: [pytypes.BytesType, pytypes.BytesBackedType],
    StackType.bytes_32: [pytypes.BytesType, pytypes.BytesBackedType],
    StackType.bytes_33: [pytypes.BytesType, pytypes.BytesBackedType],
    StackType.bytes_64: [pytypes.BytesType, pytypes.BytesBackedType],
    StackType.bytes_80: [pytypes.BytesType, pytypes.BytesBackedType],
    StackType.bytes_1232: [pytypes.BytesType, pytypes.BytesBackedType],
    StackType.bytes_1793: [pytypes.BytesType, pytypes.BytesBackedType],
    StackType.bool: [pytypes.BoolType, pytypes.UInt64Type],
    StackType.bool_only: [pytypes.BoolType],
    StackType.uint64: [pytypes.UInt64Type],
    StackType.any: [pytypes.BytesType, pytypes.UInt64Type, pytypes.BytesBackedType],
    StackType.box_name: [pytypes.BytesType, pytypes.BytesBackedType],
    StackType.address: [pytypes.AccountType],
    StackType.bigint: [pytypes.BigUIntType],
    StackType.state_key: [pytypes.BytesType, pytypes.BytesBackedType],
}


@attrs.define(kw_only=True)
class GroupedOpCodes:
    name: str
    doc: str
    ops: dict[str, str]
    """TEAL ops to include in group, mapped to their Python method name"""


GROUPED_OP_CODES = [
    GroupedOpCodes(
        name="AppGlobal",
        doc="Get or modify Global app state",
        ops={
            "app_global_get": "get",
            "app_global_get_ex": "get_ex",
            "app_global_del": "delete",
            "app_global_put": "put",
        },
    ),
    GroupedOpCodes(
        name="Scratch",
        doc="Load or store scratch values",
        ops={"loads": "load", "stores": "store"},
    ),
    GroupedOpCodes(
        name="AppLocal",
        doc="Get or modify Local app state",
        ops={
            "app_local_get": "get",
            "app_local_get_ex": "get_ex",
            "app_local_del": "delete",
            "app_local_put": "put",
        },
    ),
    GroupedOpCodes(
        name="Box",
        doc="Get or modify box state",
        ops={
            "box_create": "create",
            "box_del": "delete",
            "box_extract": "extract",
            "box_get": "get",
            "box_len": "length",
            "box_put": "put",
            "box_replace": "replace",
            "box_resize": "resize",
            "box_splice": "splice",
        },
    ),
    GroupedOpCodes(
        name="EllipticCurve",
        doc="Elliptic Curve functions",
        ops={
            "ec_add": "add",
            "ec_map_to": "map_to",
            "ec_multi_scalar_mul": "scalar_mul_multi",
            "ec_pairing_check": "pairing_check",
            "ec_scalar_mul": "scalar_mul",
            "ec_subgroup_check": "subgroup_check",
        },
    ),
    GroupedOpCodes(
        name="ITxnCreate",
        doc="Create inner transactions",
        ops={
            "itxn_begin": "begin",
            "itxn_next": "next",
            "itxn_submit": "submit",
            "itxn_field": "set",
        },
    ),
]


@attrs.define(kw_only=True)
class MergedOpCodes:
    name: str
    ops: list[str]
    doc: str | None = None
    """class docstring; if None, derived from the single op's langspec doc"""


MERGED_OP_CODES = [
    MergedOpCodes(
        name="Txn",
        doc="Get values for the current executing transaction",
        ops=["txn", "txnas"],
    ),
    MergedOpCodes(
        name="GTxn",
        doc="Get values for transactions in the current group",
        ops=["gtxns", "gtxnsas"],
    ),
    MergedOpCodes(
        name="ITxn",
        doc="Get values for the last inner transaction",
        ops=["itxn", "itxnas"],
    ),
    MergedOpCodes(
        name="GITxn",
        doc="Get values for inner transaction in the last group submitted",
        ops=["gitxn", "gitxnas"],
    ),
    MergedOpCodes(doc="Get Global values", name="Global", ops=["global"]),
    MergedOpCodes(name="AcctParamsGet", ops=["acct_params_get"]),
    MergedOpCodes(name="AppParamsGet", ops=["app_params_get"]),
    MergedOpCodes(name="AssetHoldingGet", ops=["asset_holding_get"]),
    MergedOpCodes(name="AssetParamsGet", ops=["asset_params_get"]),
    MergedOpCodes(name="Block", ops=["block"]),
    MergedOpCodes(name="JsonRef", ops=["json_ref"]),
    MergedOpCodes(name="VoterParamsGet", ops=["voter_params_get"]),
]
# TEAL op code -> Python function name. Only for Python keyword/builtin collisions;
# variant-based renames (e.g. `arg` for TEAL `args`) are derived from OP_VARIANTS by
# picking the shortest name in each family.
RENAMED_OP_CODES = {"return": "exit"}
# Most-stack-args variant -> variants with more immediates (including embedded-immediate
# variants like arg_0). The key is the variant exposed to users; the values are all other
# TEAL ops the optimiser may substitute in. Drives both "handled" bookkeeping and the list
# of related TEAL ops in generated docstrings.
OP_VARIANTS = {
    "args": ["arg", "arg_0", "arg_1", "arg_2", "arg_3"],
    "extract3": ["extract"],
    "replace3": ["replace", "replace2"],
    "substring3": ["substring"],
    "gloadss": ["gload", "gloads"],
    "gaids": ["gaid"],
    "gtxns": ["gtxn"],
    "txnas": ["txna"],
    "gtxnsas": ["gtxnsa", "gtxna", "gtxnas"],
    "itxnas": ["itxna"],
    "gitxnas": ["gitxna"],
    "loads": ["load"],
    "stores": ["store"],
    # fully excluded families: key + variants are all filtered from generation
    "intc": ["intc_0", "intc_1", "intc_2", "intc_3"],
    "bytec": ["bytec_0", "bytec_1", "bytec_2", "bytec_3"],
}
EXCLUDED_OPCODES = {
    # low level flow control
    "bnz",
    "bz",
    "b",
    "callsub",
    "retsub",
    "proto",
    "switch",
    "match",
    # low level stack manipulation
    "intc",
    "bytec",
    "pushbytes",
    "pushbytess",
    "pushint",
    "pushints",
    "frame_dig",
    "frame_bury",
    "bury",
    "cover",
    "dig",
    "dup",
    "dup2",
    "dupn",
    "pop",
    "popn",
    "swap",
    "uncover",
    # manipulates what other low level ops point to
    "intcblock",
    "bytecblock",
    # have a higher level abstraction that supersedes it
    "log",
    # specially handled
    "err",
    "assert",
    "len",
}


# ops treated as properties in the generated stubs, mapped to method names to exclude
PROPERTY_OPS: dict[str, set[str]] = {
    "global": {"opcode_budget"},
    "txn": set(),
}


@attrs.frozen
class StubArg:
    name: str
    python_type: str  # pre-rendered stub type, e.g. "UInt64 | int"
    doc: str | None


@attrs.frozen(kw_only=True)
class Method:
    name: str  # Python function/method name
    op_code: str  # TEAL opcode referenced by the method
    doc: list[str]
    return_docs: list[str]
    min_avm_version: int
    stub_args: list[StubArg]
    # None => halts; [] => returns None; else result stack types
    result_types: list[pytypes.RuntimeType] | None
    # awst mapping: positional immediate literals, or expected immediate type
    immediates: list[str | type[str | int]]
    # awst mapping: per-call-arg expected pytypes, or int index into `immediates`
    arg_mappings: list[tuple[pytypes.PyType, ...] | int]
    is_property: bool

    @property
    def result_pytype(self) -> pytypes.PyType:
        return result_types_to_pytype(self.result_types)


@attrs.frozen(kw_only=True)
class ClassSpec:
    name: str
    doc: str
    ops: list[str]  # sorted TEAL opcodes covered by this class (for docstring)
    methods: list[Method]


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------


def main() -> None:
    spec_path = VCS_ROOT / "langspec.puya.json"
    spec_text = spec_path.read_text(encoding="utf-8")
    spec_json = json.loads(spec_text)
    spec = LanguageSpec.from_json(spec_json)

    handled = EXCLUDED_OPCODES.union(*OP_VARIANTS.values())
    top_level = list[Method]()
    classes = list[ClassSpec]()
    enums = dict[str, None]()

    for merged in MERGED_OP_CODES:
        handled.update(merged.ops)
        classes.append(_build_merged_class(spec, merged))
    for grouped in GROUPED_OP_CODES:
        handled.update(grouped.ops)
        classes.append(_build_grouped_class(spec, grouped, enums))
    for op in spec.ops.values():
        if op.name in handled or not op.name.isidentifier():
            logger.info(f"Ignoring: {op.name}")
        else:
            # derive Python name: explicit rename, else shortest name in OP_VARIANTS family
            # (e.g. TEAL `args` becomes Python `arg()`), else the op name itself.
            if op_variants := OP_VARIANTS.get(op.name):
                py_name = min(op.name, *op_variants, key=len)
            else:
                py_name = RENAMED_OP_CODES.get(op.name, op.name)
            _collect_stack_arg_enums(op, enums)
            top_level.extend(_methods_for_op(op, py_name))

    top_level.sort(key=lambda m: m.name)
    classes.sort(key=lambda c: c.name)
    enum_names = list(enums)

    _write_stub(spec, enum_names, top_level, classes)
    _write_awst_data(spec, enum_names, top_level, classes)


# ---------------------------------------------------------------------------
# Method construction
# ---------------------------------------------------------------------------


def _methods_for_op(op: Op, py_name: str) -> Iterator[Method]:
    """Build methods for ``op``; forks into bytes/uint64 variants if an output is `any`."""
    if any(so.stack_type is StackType.any for so in op.stack_outputs):
        logger.info(f"Found any output for {op.name}")
        for replacement in (StackType.bytes, StackType.uint64):
            yield _build_method(_replace_any(op, replacement), f"{py_name}_{replacement.name}")
    else:
        yield _build_method(op, py_name)
    logger.info(f"Mapping {op.name} to {py_name}")


def _methods_for_overriding_immediate(
    spec: LanguageSpec, op: Op, immediate: Immediate, *, method_name_prefix: str = ""
) -> Iterator[Method]:
    """Build one method per value of an arg-enum immediate that swaps stack types."""
    assert immediate.arg_enum
    logger.info(f"Using overriding immediate for {op.name}")
    for value in spec.arg_enums[immediate.arg_enum]:
        assert value.stack_type
        # The immediate value swaps exactly one stack input or output's type.
        if immediate.modifies_stack_input is not None:
            inputs = list(op.stack_inputs)
            idx = immediate.modifies_stack_input
            inputs[idx] = attrs.evolve(inputs[idx], stack_type=value.stack_type, doc=value.doc)
            per_value_op = attrs.evolve(op, stack_inputs=inputs)
        else:
            assert immediate.modifies_stack_output is not None
            outputs = list(op.stack_outputs)
            idx = immediate.modifies_stack_output
            outputs[idx] = attrs.evolve(outputs[idx], stack_type=value.stack_type, doc=value.doc)
            per_value_op = attrs.evolve(op, stack_outputs=outputs)

        method_name = _snake_case(value.name)
        if method_name_prefix:
            method_name = f"{method_name_prefix}_{method_name}"
        # Enums may be reused across ops; take the max minimum version of op and enum value.
        method_version = max(op.min_avm_version, value.min_avm_version)
        method = _build_method(per_value_op, method_name, pinned_immediate=(immediate, value))
        yield attrs.evolve(
            method,
            min_avm_version=method_version,
            doc=method.doc + _min_version_note(method_version),
        )


def _build_method(
    op: Op, py_name: str, *, pinned_immediate: tuple[Immediate, ArgEnum] | None = None
) -> Method:
    stub_args = list[StubArg]()
    immediates = list[str | type[str | int]]()
    arg_mappings = list[tuple[pytypes.PyType, ...] | int]()

    for imm_idx, imm in enumerate(op.immediate_args):
        if pinned_immediate and pinned_immediate[0] == imm:
            # pinned: omit from stub signature, inline the enum value in the awst mapping
            immediates.append(pinned_immediate[1].name)
            continue
        if imm.immediate_type == ImmediateKind.arg_enum:
            assert imm.arg_enum, "Arg enum expected"
            stub_type = _enum_class(imm.arg_enum)
        else:
            stub_type = _immediate_kind_pytype(imm.immediate_type).__name__
        stub_args.append(StubArg(name=imm.name.lower(), python_type=stub_type, doc=imm.doc))
        immediates.append(_immediate_kind_pytype(imm.immediate_type))
        arg_mappings.append(imm_idx)

    for si in op.stack_inputs:
        stub_args.append(
            StubArg(
                name=si.name.lower(), python_type=_stack_python_type(si.stack_type), doc=si.doc
            )
        )
        arg_mappings.append(tuple(_stack_type_pytypes(si.stack_type)))

    doc = [] if pinned_immediate else _op_doc(op)

    if op.halts:
        return_docs = ["Halts program"]
        result_types = None
    else:
        return_docs = [so.doc for so in op.stack_outputs if so.doc]
        if not op.stack_outputs:
            result_types = list[pytypes.RuntimeType]()
        elif py_name == "on_completion":
            result_types = [pytypes.OnCompleteActionType]
        elif py_name == "type_enum":
            result_types = [pytypes.TransactionTypeType]
        else:
            result_types = [_result_pytype(o.stack_type) for o in op.stack_outputs]

    is_property = op.name in PROPERTY_OPS and py_name not in PROPERTY_OPS[op.name]

    return Method(
        name=py_name,
        op_code=op.name,
        doc=doc,
        return_docs=return_docs,
        min_avm_version=op.min_avm_version,
        stub_args=stub_args,
        result_types=result_types,
        immediates=immediates,
        arg_mappings=arg_mappings,
        is_property=is_property,
    )


def _build_merged_class(spec: LanguageSpec, group: MergedOpCodes) -> ClassSpec:
    # later op wins on name collision; dict preserves first-insertion order
    methods = dict[str, Method]()
    for op_name in group.ops:
        op = spec.ops[op_name]
        overriding = _overriding_immediate(op)
        assert overriding
        for method in _methods_for_overriding_immediate(spec, op, overriding):
            methods[method.name] = method
    doc = group.doc
    if doc is None:
        doc = " ".join(line for op_name in group.ops for line in spec.ops[op_name].doc)
    return ClassSpec(
        name=group.name, doc=doc, ops=sorted(group.ops), methods=list(methods.values())
    )


def _build_grouped_class(
    spec: LanguageSpec, group: GroupedOpCodes, enums: dict[str, None]
) -> ClassSpec:
    methods = list[Method]()
    for op_name, py_name in group.ops.items():
        op = spec.ops[op_name]
        overriding = _overriding_immediate(op)
        if overriding:
            methods.extend(
                _methods_for_overriding_immediate(spec, op, overriding, method_name_prefix=py_name)
            )
        else:
            methods.extend(_methods_for_op(op, py_name))
        _collect_stack_arg_enums(op, enums)
    return ClassSpec(name=group.name, doc=group.doc, ops=sorted(group.ops), methods=methods)


def _replace_any(op: Op, replace: StackType) -> Op:
    return attrs.evolve(
        op,
        stack_inputs=[
            attrs.evolve(si, stack_type=replace) if si.stack_type is StackType.any else si
            for si in op.stack_inputs
        ],
        stack_outputs=[
            attrs.evolve(so, stack_type=replace) if so.stack_type is StackType.any else so
            for so in op.stack_outputs
        ],
    )


def _collect_stack_arg_enums(op: Op, enums: dict[str, None]) -> None:
    for arg in op.immediate_args:
        if (
            arg.immediate_type == ImmediateKind.arg_enum
            and arg.modifies_stack_input is None
            and arg.modifies_stack_output is None
        ):
            assert arg.arg_enum is not None
            enums[arg.arg_enum] = None


def _overriding_immediate(op: Op) -> Immediate | None:
    return next(
        (
            i
            for i in op.immediate_args
            if i.modifies_stack_input is not None or i.modifies_stack_output is not None
        ),
        None,
    )


# ---------------------------------------------------------------------------
# Type / string helpers
# ---------------------------------------------------------------------------


def _stack_type_pytypes(st: StackType) -> Sequence[pytypes.PyType]:
    try:
        return STACK_TYPE_MAPPING[st]
    except KeyError as ex:
        raise NotImplementedError(f"Could not map stack type {st} to an algopy type") from ex


def _result_pytype(st: StackType) -> pytypes.RuntimeType:
    assert st is not StackType.any
    pt = _stack_type_pytypes(st)[0]
    assert isinstance(pt, pytypes.RuntimeType)
    return pt


def _stack_python_type(st: StackType) -> str:
    """Python type annotation (union) for a stack type in a stub signature."""
    allowed = _stack_type_pytypes(st)
    # Hide types that are subtypes of another type in the list
    # (e.g. Bytes is redundant when BytesBacked is present, because Bytes is a BytesBacked).
    displayed = [t for t in allowed if not any(other < t for other in allowed if other != t)]
    names = [str(pt).removeprefix("algopy.") for pt in displayed]
    for pt in displayed:
        lit = PYTYPE_TO_LITERAL[pt]
        if lit is not None and (lit_name := str(lit)) not in names:
            names.append(lit_name)
    return " | ".join(names)


def _immediate_kind_pytype(kind: ImmediateKind) -> type[int | str]:
    match kind:
        case ImmediateKind.uint8 | ImmediateKind.int8 | ImmediateKind.varuint:
            return int
        case ImmediateKind.arg_enum:
            return str
        case _:
            raise ValueError(f"Unexpected ImmediateKind: {kind}")


def _enum_class(arg_enum: str) -> str:
    if (override := PYTHON_ENUM_CLASS.get(arg_enum)) is not None:
        return override
    # don't change acronyms
    if arg_enum.isupper():
        return arg_enum
    return _snake_case(arg_enum).replace("_", " ").title().replace(" ", "")


# HACK: these variants are hidden from docstrings — optimiser-picked alternates that are
# noise to users. Covers embedded-immediate forms (e.g. arg_0) via the regex, plus explicit
# names that don't match a pattern.
_DOC_HIDDEN_VARIANT_RE = re.compile(r"_\d+$")
_DOC_HIDDEN_VARIANTS = {"load", "store", "replace"}


def _op_codes_for_doc_links(op_name: str) -> list[str]:
    variants = [
        v
        for v in OP_VARIANTS.get(op_name, ())
        if v not in _DOC_HIDDEN_VARIANTS and not _DOC_HIDDEN_VARIANT_RE.search(v)
    ]
    return sorted({op_name, *variants})


def _algorand_doc(op: str) -> str:
    return f"[`{op}`]({ALGORAND_OP_URL}#{op})"


def _op_doc(op: Op) -> list[str]:
    doc = [d.replace("\\", "\\\\") for d in op.doc]
    return doc + _min_version_note(op.min_avm_version)


def _min_version_note(version: int) -> list[str]:
    # only output min AVM version if it exceeds the base supported version
    return [f"Min AVM version: {version}"] if version > MIN_SUPPORTED_VERSION else []


def _snake_case(s: str) -> str:
    s = s.replace("-", " ")
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", s)
    s = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", s)
    return re.sub(r"[-\s]", "_", s).lower()


def _pytype_stub_repr(pt: pytypes.PyType) -> str:
    return str(pt).replace("algopy.", "")


# ---------------------------------------------------------------------------
# Stub rendering (op.pyi)
# ---------------------------------------------------------------------------


_ERR_FUNCTION_STUB = '''

def err(message: typing.LiteralString | None = None, /) -> typing.Never:
    """
    Fail immediately.
    :returns typing.Never: Halts program

    Native TEAL opcode: [`err`](https://dev.algorand.co/reference/algorand-teal/opcodes/#err)
    """

'''


def _render_enum_stub(spec: LanguageSpec, arg_enum: str) -> str:
    enum_name = _enum_class(arg_enum)
    lines = [
        f"class {enum_name}(str):",
        f'{INDENT}"""Available values for the `{arg_enum}` enum"""',
    ]
    for value in spec.arg_enums[arg_enum]:
        lines.append(f"{INDENT}{value.name}: {enum_name} = ...")
        value_doc = ([value.doc] if value.doc else []) + _min_version_note(value.min_avm_version)
        if value_doc:
            lines.append(f'{INDENT}"""')
            lines.extend(f"{INDENT}{line}" for line in value_doc)
            lines.append(f'{INDENT}"""')
    lines.append("")
    return "\n".join(lines)


def _render_method_stub(method: Method, prefix: str = "") -> str:
    returns = _pytype_stub_repr(method.result_pytype)
    args = [f"{a.name}: {a.python_type}" for a in method.stub_args]
    if args:
        args.append("/")  # TODO: remove once we support kwargs
    signature = f"{prefix}def {method.name}({', '.join(args)}) -> {returns}:"
    doc = list(method.doc)
    doc.extend(f":param {a.python_type} {a.name}: {a.doc}" for a in method.stub_args if a.doc)
    if method.return_docs:
        if doc:
            doc.append(f":returns {returns}: {method.return_docs[0]}")
            doc.extend(method.return_docs[1:])
        else:
            doc = list(method.return_docs)
    teal_refs = ", ".join(_algorand_doc(op) for op in _op_codes_for_doc_links(method.op_code))
    doc.extend(("", f"Native TEAL opcode: {teal_refs}"))
    body_lines = ['"""', *doc, '"""'] if doc else ["..."]
    body_indent = prefix + INDENT
    body = "\n".join(body_indent + line for line in body_lines)
    return f"{signature}\n{body}"


def _render_class_var_stub(method: Method, indent: str) -> str:
    returns = _pytype_stub_repr(method.result_pytype)
    doc = method.return_docs or method.doc
    doc = list(doc) + _min_version_note(method.min_avm_version)
    lines = [
        f"{indent}{method.name}: typing.Final[{returns}] = ...",
        f'{indent}"""',
        *(f"{indent}{line}" for line in doc),
        f'{indent}"""',
    ]
    return "\n".join(lines)


def _render_class_stub(klass: ClassSpec) -> str:
    op_refs = [_algorand_doc(op) for op in klass.ops]
    lines = [
        f"class {klass.name}:",
        INDENT + '"""',
        INDENT + klass.doc,
        INDENT + f"Native TEAL op{'s' if len(op_refs) > 1 else ''}: {', '.join(op_refs)}",
        INDENT + '"""',
    ]
    for method in klass.methods:
        if method.is_property:
            lines.append(_render_class_var_stub(method, INDENT))
        else:
            lines.append(f"{INDENT}@staticmethod")
            lines.append(_render_method_stub(method, prefix=INDENT))
        lines.append("")
    return "\n".join(lines)


def _write_stub(
    spec: LanguageSpec, enums: list[str], top_level: list[Method], classes: list[ClassSpec]
) -> None:
    references = ", ".join(
        sorted(
            str(pt).removeprefix("algopy.")
            for pt in PYTYPE_TO_LITERAL
            if str(pt).startswith("algopy.")
        )
    )
    out = [
        autogenerated_header_for(__file__),
        "import typing",
        "",
        f"from algopy import {references}",
    ]
    out.extend(_render_enum_stub(spec, e) for e in enums)
    for method in top_level:
        if method.name == "exit":
            out.append(_ERR_FUNCTION_STUB)
        out.append(_render_method_stub(method))
    out.extend(_render_class_stub(c) for c in classes)

    path = VCS_ROOT / "stubs" / "algopy-stubs" / "op.pyi"
    path.write_text("\n".join(out), encoding="utf-8")
    subprocess.run(["ruff", "format", str(path)], check=True, cwd=VCS_ROOT)


# ---------------------------------------------------------------------------
# AWST data rendering (intrinsic_data.py)
# ---------------------------------------------------------------------------


def _pytype_repr(typ: pytypes.PyType) -> str:
    try:
        return PYTYPE_REPR[typ]
    except KeyError:
        pass
    match typ:
        case pytypes.TupleType(items=items) if len(items) > 1:
            inner = ", ".join(_pytype_repr(t) for t in items)
            return f"pytypes.GenericTupleType.parameterise(({inner}), source_location=None)"
    raise ValueError(f"Unexpected pytype: {typ}")


def _immediate_repr(item: str | int | type[str | int]) -> str:
    return item.__name__ if isinstance(item, type) else repr(item)


def _arg_repr(arg: Sequence[pytypes.PyType] | int) -> str:
    if isinstance(arg, int):
        return repr(arg)
    inner = ", ".join(_pytype_repr(t) for t in arg)
    return f"({inner},)" if len(arg) == 1 else f"({inner})"


def _render_op_mapping(method: Method) -> str:
    if method.is_property:
        (immediate,) = method.immediates
        return (
            f"{method.name}=PropertyOpMapping("
            f"{method.op_code!r}, {immediate!r}, {_pytype_repr(method.result_pytype)},"
            f"),"
        )
    parts = [f"op_code={method.op_code!r}"]
    if method.result_types is None:
        parts.append("result=None")
    elif method.result_types:
        parts.append(f"result=[{', '.join(_pytype_repr(r) for r in method.result_types)}]")
    if method.immediates:
        parts.append(f"immediates=[{', '.join(_immediate_repr(i) for i in method.immediates)}]")
    if method.arg_mappings:
        parts.append(f"args=[{', '.join(_arg_repr(a) for a in method.arg_mappings)}]")
    return f"{method.name}=FunctionOpMapping({', '.join(parts)},),"


def _build_awst_data(
    spec: LanguageSpec, enums: list[str], top_level: list[Method], classes: list[ClassSpec]
) -> str:
    lines = [
        autogenerated_header_for(__file__),
        "import typing",
        "from collections.abc import Mapping, Sequence",
        "from puyapy.awst_build import pytypes",
        "from puyapy.awst_build.intrinsic_models import FunctionOpMapping, PropertyOpMapping",
        "ENUM_CLASSES: typing.Final[Mapping[str, Mapping[str, str]]] = dict(",
    ]
    for enum_name in enums:
        lines.append(f"{_enum_class(enum_name)}=dict(")
        # enum names currently match enum immediate values
        lines.extend(f'{v.name}="{v.name}",' for v in spec.arg_enums[enum_name])
        lines.append("),")
    lines.append(")")
    lines.append("")
    lines.append("FUNC_TO_AST_MAPPER: typing.Final[Mapping[str, FunctionOpMapping]] = dict(")
    lines.extend(_render_op_mapping(m) for m in top_level)
    lines.append(")")
    lines.append(
        "NAMESPACE_CLASSES: "
        "typing.Final[Mapping[str, Mapping[str, PropertyOpMapping | FunctionOpMapping]]]"
        " = dict("
    )
    for klass in classes:
        lines.append(f"{klass.name}=dict(")
        lines.extend(_render_op_mapping(m) for m in klass.methods)
        lines.append("),")
    lines.append(")")
    return "\n".join(lines)


def _write_awst_data(
    spec: LanguageSpec, enums: list[str], top_level: list[Method], classes: list[ClassSpec]
) -> None:
    path = VCS_ROOT / "src" / "puyapy" / "awst_build" / "intrinsic_data.py"
    path.write_text(_build_awst_data(spec, enums, top_level, classes), encoding="utf-8")
    subprocess.run(["ruff", "format", str(path)], check=True, cwd=VCS_ROOT)
    subprocess.run(["ruff", "check", "--fix", str(path)], check=False, cwd=VCS_ROOT)


if __name__ == "__main__":
    main()
