#!/usr/bin/env python3
import subprocess
import sys
import typing
from pathlib import Path

import mypy.build
import mypy.find_sources
import mypy.nodes

from puya.log import configure_stdio
from puyapy.parse_mypy import _get_mypy_options

THIS_PATH = Path(__file__)
SCRIPTS_DIR = THIS_PATH.parent
VCS_ROOT = SCRIPTS_DIR.parent
SRC_DIR = VCS_ROOT / "src"
STUBS_DIR = VCS_ROOT / "stubs" / "algopy-stubs"


class SymbolData(typing.NamedTuple):
    fullname: str
    module_public: bool


def main() -> int:
    configure_stdio()
    mypy_opts = _get_mypy_options()
    mypy_opts.python_executable = sys.executable
    source_list = mypy.find_sources.create_source_list([str(STUBS_DIR)], mypy_opts)
    result = mypy.build.build(source_list, options=mypy_opts)
    symbol_tables = dict[str, dict[str, SymbolData]]()
    for module_name, mypy_file in result.files.items():
        if module_name.partition(".")[0] in ("algopy", "abc", "typing", "typing_extensions"):
            assert module_name not in symbol_tables
            module_symtable = dict[str, SymbolData]()
            symbol_tables[module_name] = module_symtable
            for symbol_name, symbol in mypy_file.names.items():
                if not (
                    symbol.module_hidden
                    or (symbol_name.startswith("__") and symbol_name.endswith("__"))
                ):
                    assert not (symbol.module_public and symbol.module_hidden)
                    assert symbol.kind == mypy.nodes.GDEF
                    assert symbol.fullname
                    module_symtable[symbol_name] = SymbolData(
                        symbol.fullname, symbol.module_public
                    )
    assert not result.errors
    output_path = SRC_DIR / "puyapy" / "_stub_symtables.py"
    output_lines = [
        f"# AUTO GENERATED BY {THIS_PATH.relative_to(VCS_ROOT)}, DO NOT EDIT",
        "import typing",
        "from collections.abc import Mapping",
        'SymbolData = typing.NamedTuple("SymbolData", [("fullname", str), ("module_public", bool)])',  # noqa: E501
        f"STUB_SYMTABLES: typing.Final[Mapping[str, Mapping[str, SymbolData]]] = {symbol_tables!r}",  # noqa: E501
    ]
    output_path.write_text("\n".join(output_lines), encoding="utf-8")
    subprocess.run(["ruff", "format", str(output_path)], check=True, cwd=VCS_ROOT)
    subprocess.run(["ruff", "check", "--fix", str(output_path)], check=True, cwd=VCS_ROOT)
    subprocess.run(["ruff", "format", str(output_path)], check=True, cwd=VCS_ROOT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
