from pathlib import Path

from puya.utils import normalise_path_to_str

SCRIPTS_DIR = Path(__file__).parent
VCS_ROOT = SCRIPTS_DIR.parent


def autogenerated_header_for(script_path: str) -> str:
    script_path = normalise_path_to_str(Path(script_path).relative_to(VCS_ROOT))
    return f"# AUTO GENERATED BY {script_path}, DO NOT EDIT"
