name: "Setup Python venv"
description: "Setup Python, install uv, install dependencies, and activate venv"
inputs:
  python_version:
    description: "The Python version to use"
    default: "3.13"
    required: false
  uv_sync_args:
    description: "Additional args to pass to uv install command"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: ${{ inputs.python_version }}
        activate-environment: true

    - name: Install dependencies
      shell: bash
      run: uv sync ${{ inputs.uv_sync_args }}
